dist:
  - xenial
git:
  depth: 3
  submodules: false
language: python
python:
  - "2.7"
  - "3.7"
matrix:  # macos can't be listed in 'os' as we need to set 'generic' as language (because travis doesn't support python on macos for now)
  include:
    - os: osx
      language: generic
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - travis_wait 45 choco install -y msys2
        - travis_wait 45 choco install -y python
        - travis_wait 45 choco install -y cppcheck
        - travis_wait 45 choco install -y pip 
cache: pip
install:
  - pip install -r tests/sources/requirements.txt
  - pip install -r docs/tests/requirements.txt
addons:
  apt:
    packages:
      - clang-format-5.0
  homebrew:
    packages:
      - clang-format
      - cppcheck
      - python
script:
  - C:\tools\msys64\usr\bin\bash -lc ls
  - python -m unittest discover -s tests/sources
  - python -m unittest discover -s docs/tests
