dist:
  - xenial
git:
  depth: 3
  submodules: false
language: python
python:
  - "2.7"
  - "3.7"
matrix:  # macos can't be listed in 'os' as we need to set 'generic' as language (because travis doesn't support python on macos for now)
  include:
    - os: osx
      language: generic
    - os: windows
      language: generic
cache: pip
install:
  - pip install -r tests/sources/requirements.txt
  - pip install -r docs/tests/requirements.txt
addons:
  apt:
    packages:
      - clang-format-5.0
  homebrew:
    packages:
      - clang-format
      - python
script:
  - python -m unittest discover -s tests/sources
  - python -m unittest discover -s docs/tests
